# Generated by Django 3.2 on 2022-04-03 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('instructor', models.IntegerField()),
                ('sections', django_mysql.models.ListTextField(models.IntegerField(), blank=True, max_length=50, null=True, size=10)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('locations', models.CharField(blank=True, max_length=25, null=True)),
                ('description', models.CharField(max_length=255)),
                ('total', models.IntegerField(default=0)),
                ('out', models.IntegerField(default=0)),
                ('available', models.IntegerField(default=0)),
                ('ser_no', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TimeStamp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.IntegerField()),
                ('item_id', models.IntegerField()),
                ('checkout_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('myClass', models.IntegerField(blank=True, null=True)),
                ('section', models.IntegerField(blank=True, null=True)),
                ('team', models.CharField(blank=True, max_length=50, null=True)),
                ('itemsCount', models.JSONField(blank=True, default=dict)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(blank=True, related_name='users', to='core.Item')),
            ],
        ),
    ]
