# Generated by Django 3.2.8 on 2022-02-05 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('instructor', models.IntegerField()),
                ('sections', django_mysql.models.ListTextField(models.IntegerField(), blank=True, max_length=50, null=True, size=10)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Instruct',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('sections', django_mysql.models.ListTextField(models.IntegerField(), size=100)),
                ('classes', django_mysql.models.ListTextField(models.IntegerField(), size=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('total', models.IntegerField(default=1)),
                ('out', models.IntegerField(default=0)),
                ('available', models.IntegerField(default=1)),
                ('ser_no', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('section', models.IntegerField()),
                ('team', models.CharField(max_length=50)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(blank=True, related_name='users', to='core.Item')),
            ],
        ),
    ]
