# Generated by Django 3.2.8 on 2022-02-05 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='instructor',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
