# Generated by Django 3.2.8 on 2022-01-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('ser_no', models.CharField(max_length=255)),
            ],
        ),
    ]
