# Generated by Django 3.2.8 on 2022-01-31 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruct',
            name='sections',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
