# Generated by Django 3.2.8 on 2022-01-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='users', to='core.Item'),
        ),
    ]
