# Generated by Django 3.2.8 on 2022-02-02 23:15

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220202_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='instructor',
            field=django_mysql.models.ListTextField(models.PositiveSmallIntegerField(), blank=True, max_length=100, null=True, size=100),
        ),
        migrations.AlterField(
            model_name='classes',
            name='sections',
            field=django_mysql.models.ListTextField(models.PositiveSmallIntegerField(), blank=True, max_length=100, null=True, size=100),
        ),
    ]
