# Generated by Django 3.2.8 on 2022-01-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_account_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='available',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='out',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
