# Generated by Django 3.2.8 on 2022-01-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220101_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='available',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='out',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='total',
            field=models.IntegerField(default=1),
        ),
    ]
