# Generated by Django 3.2.8 on 2022-01-07 05:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_auto_20220107_0537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='instructor',
        ),
        migrations.AddField(
            model_name='account',
            name='instructor',
            field=models.ManyToManyField(blank=True, related_name='instructor', to=settings.AUTH_USER_MODEL),
        ),
    ]
