# Generated by Django 3.2.8 on 2022-01-07 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_auto_20220107_0541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='instructor',
        ),
        migrations.AddField(
            model_name='account',
            name='instructor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to='auth.user'),
            preserve_default=False,
        ),
    ]
