# Generated by Django 3.2.8 on 2022-01-07 17:26

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0007_auto_20220107_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instruct',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('sections', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=1), size=None)),
            ],
        ),
    ]
