# Generated by Django 3.2 on 2022-01-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.AddField(
            model_name='instruct',
            name='sections',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
