# Generated by Django 3.2.8 on 2022-01-21 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_auto_20220120_0540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('classnumber', models.CharField(max_length=4)),
                ('sectionnumber', models.IntegerField(primary_key=True, serialize=False)),
                ('students', models.ManyToManyField(related_name='students', to='core.Account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Instruct',
        ),
    ]
