# Generated by Django 3.2 on 2022-01-26 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_instruct_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='To Delete', upload_to=''),
            preserve_default=False,
        ),
    ]
