# Generated by Django 3.2.8 on 2022-01-21 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20220121_0325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='classnumber',
            new_name='class_no',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='sectionnumber',
            new_name='section_no',
        ),
    ]
