# Generated by Django 3.2.8 on 2022-01-21 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20220121_0327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='ser_no',
            new_name='serial_no',
        ),
    ]
