# Generated by Django 3.2.8 on 2022-01-21 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_ser_no_item_serial_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='students',
            field=models.ManyToManyField(related_name='section_no', to='core.Account'),
        ),
    ]
