# Generated by Django 3.2.8 on 2022-01-21 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_section_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='students',
            field=models.ManyToManyField(related_name='sections', to='core.Account'),
        ),
    ]
