# Generated by Django 3.2.8 on 2022-01-21 03:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0015_alter_section_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='sections', to=settings.AUTH_USER_MODEL),
        ),
    ]
