export const ADD_ACCOUNT = "ADD_ACCOUNT"
export const SET_ACCOUNT = "SET_ACCOUNT"
export const RESET_ACCOUNT = "RESET_ACCOUNT"
export const DELETE_ACCOUNT = "DELETE_ACCOUNT"
export const IS_SET = "IS_SET"
